# Generated by Django 3.0.6 on 2020-05-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='date published'),
        ),
    ]
