# Generated by Django 3.0.6 on 2020-05-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_image_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
