# Generated by Django 3.0.6 on 2020-05-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20200523_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='image',
        ),
    ]
